module.exports = [
    {
        "name": "Budapest",
        "local_names": {
            "tg": "Будапешт",
            "ku": "Budapeşt",
            "zh": "布達佩斯",
            "oc": "Budapèst",
            "uk": "Будапешт",
            "ht": "Boudapès",
            "nl": "Boedapest",
            "ug": "Budapésht",
            "ro": "Budapesta",
            "ur": "بوداپست",
            "pt": "Budapeste",
            "bg": "Будапеща",
            "en": "Budapest",
            "ta": "புடாபெஸ்ட்",
            "uz": "Budapesht",
            "ja": "ブダペスト",
            "lv": "Budapešta",
            "lt": "Budapeštas",
            "bs": "Budimpešta",
            "bn": "বুদাপেস্ট",
            "ml": "ബുഡാപെസ്റ്റ്",
            "kn": "ಬುಡಾಪೆಸ್ಟ್",
            "eo": "Budapeŝto",
            "hr": "Budimpešta",
            "gu": "બુડાપેસ્ટ",
            "it": "Budapest",
            "fr": "Budapest",
            "sq": "Budapesti",
            "tr": "Budapeşte",
            "fa": "بوداپست",
            "kv": "Будапешт",
            "av": "Будапешт",
            "mr": "बुडापेस्ट",
            "pl": "Budapeszt",
            "bo": "བུ་ད་ཕེ་སིད།",
            "ar": "بودابست",
            "de": "Budapest",
            "el": "Βουδαπέστη",
            "hu": "Budapest",
            "tt": "Будапешт",
            "ca": "Budapest",
            "be": "Будапешт",
            "ru": "Будапешт",
            "os": "Будапешт",
            "sr": "Будимпешта",
            "my": "ဗူးဒပက်မြို့",
            "sv": "Budapest",
            "hy": "Բուդապեշտ",
            "es": "Budapest",
            "am": "ቡዳፔስት",
            "gr": "Βουδαπέστη",
            "th": "บูดาเปสต์",
            "is": "Búdapest",
            "ka": "ბუდაპეშტი",
            "fy": "Boedapest",
            "cs": "Budapešť",
            "hi": "बुडापेस्ट",
            "mn": "Будапешт",
            "yi": "בודאפעשט",
            "ps": "بوډاپسټ",
            "cv": "Будапешт",
            "az": "Budapeşt",
            "ga": "Búdaipeist",
            "sk": "Budapešť",
            "he": "בודפשט",
            "no": "Budapest",
            "kk": "Будапешт",
            "la": "Budapestinum",
            "af": "Boedapest",
            "mk": "Будимпешта",
            "sl": "Budimpešta",
            "ko": "부다페스트",
            "sh": "Budimpešta",
            "li": "Boedapes"
        },
        "lat": 47.4979937,
        "lon": 19.0403594,
        "country": "HU"
    },
    {
        "name": "Gyor",
        "local_names": {
            "ka": "დიორი",
            "uk": "Дьйор",
            "ru": "Дьёр",
            "en": "Gyor",
            "sk": "Ráb",
            "hu": "Győr",
            "sr": "Ђер",
            "de": "Raab",
            "tr": "Yanıkkale",
            "la": "Arrabona"
        },
        "lat": 47.687609,
        "lon": 17.6346815,
        "country": "HU"
    },
    {
        "name": "Debrecen",
        "local_names": {
            "uk": "Дебречин",
            "ru": "Дебрецен",
            "de": "Debrezin",
            "hu": "Debrecen",
            "cs": "Debrecín",
            "sr": "Дебрецин",
            "pl": "Debreczyn",
            "sk": "Debrecín",
            "ro": "Debrețin",
            "ar": "دبرتسن"
        },
        "lat": 47.531399,
        "lon": 21.6259782,
        "country": "HU"
    },
    {
        "name": "Miskolc",
        "local_names": {
            "pl": "Miszkolc",
            "uk": "Мішкольц",
            "ro": "Mișcolț",
            "fa": "میشکولتس",
            "ko": "미슈콜츠",
            "ru": "Мишкольц",
            "ka": "მიშკოლცი",
            "bg": "Мишколц",
            "cs": "Miškovec",
            "ja": "ミシュコルツ",
            "zh": "米什科尔茨",
            "mk": "Мишколц",
            "hu": "Miskolc",
            "sk": "Miškovec",
            "hr": "Miškolc",
            "sr": "Мишколц",
            "de": "Mischkolz",
            "lt": "Miškolcas",
            "ar": "ميشكولتس",
            "lv": "Miškolca",
            "he": "מישקולץ"
        },
        "lat": 48.1030643,
        "lon": 20.7900429,
        "country": "HU"
    },
    {
        "name": "Pécs",
        "local_names": {
            "hu": "Pécs",
            "zh": "佩奇",
            "cs": "Pětikostelí",
            "pl": "Pecz",
            "uk": "Печ",
            "la": "Quinque Ecclesiae",
            "hr": "Pečuh",
            "ru": "Печ",
            "sr": "Печуј",
            "sk": "Päťkostolie",
            "de": "Fünfkirchen",
            "it": "Cinquechiese"
        },
        "lat": 46.0765883,
        "lon": 18.2280397,
        "country": "HU"
    },
    {
        "name": "Sopron",
        "local_names": {
            "sk": "Šopron",
            "it": "Odenburgo",
            "he": "שופרון",
            "la": "Scarbantia",
            "ja": "ショプロン",
            "ka": "შოპრონი",
            "hr": "Šopron",
            "hu": "Sopron",
            "ru": "Шопрон",
            "de": "Ödenburg",
            "sr": "Шопрон",
            "cs": "Šoproň"
        },
        "lat": 47.685,
        "lon": 16.5905,
        "country": "HU"
    },
    {
        "name": "Szeged",
        "local_names": {
            "mk": "Сегедин",
            "ce": "Сегед",
            "pl": "Segedyn",
            "zh": "塞格德",
            "tt": "Сегед",
            "ka": "სეგედი",
            "sr": "Сегедин",
            "uk": "Сегед",
            "ko": "세게드",
            "sk": "Segedín",
            "th": "แซแก็ด",
            "ja": "セゲド",
            "lv": "Segeda",
            "tr": "Segedin",
            "hu": "Szeged",
            "el": "Σέγκεντ",
            "lt": "Segedas",
            "az": "Seqed",
            "fa": "سگد",
            "he": "סגד",
            "ar": "زيجيد",
            "it": "Seghedino",
            "de": "Szegedin",
            "bg": "Сегед",
            "la": "Partiscum",
            "hy": "Սեգեդ",
            "yi": "סעגעד",
            "mr": "सेगेड",
            "hr": "Segedin",
            "ro": "Seghedin",
            "be": "Сегед",
            "ru": "Сегед"
        },
        "lat": 46.2546312,
        "lon": 20.1486016,
        "country": "HU"
    },
    {
        "name": "Gyékényes",
        "local_names": {
            "hu": "Gyékényes",
            "hr": "Džikeniš",
            "ru": "Дьекеньеш"
        },
        "lat": 46.2371661,
        "lon": 17.0090208,
        "country": "HU"
    }
]